networks:
  isolation-network:
    driver: bridge

services:
  dataloader:
    build: data
    volumes:
      - ./data/checkpoints:/home/data/checkpoints
  
  text_generator:
    build: text_generator
    volumes:
      - ./data/checkpoints:/home/text_generator/checkpoints
    ports:
      - "5001:5001"
    networks:
      - isolation-network
    depends_on:
      - dataloader
      
  telegram_bot:
    build: telegram_bot
    networks:
      - isolation-network
    depends_on:
      - text_generator
