networks:
  isolation-network:
    driver: bridge

services:
  text_generator:
    build: text_generator
    ports:
      - "5000:5000"
    volumes:
      - ./text_generator/main.py:/main.py
    networks:
      - isolation-network
      
  telegram_bot:
    build: telegram_bot
    volumes:
      - ./telegram_bot/main.py:/main.py
    networks:
      - isolation-network
    depends_on:
      - text_generator
